### ISSUE TITLE
PROBLEM: Basic checks: Using telnet, curl, prepared files, demonstrate that the following features work properly: For every test you should receive the appropriate status code.

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#60]
Is it enough to see the status code f.e. in Postman, or shall we print it also in the terminal?

Tested: localhost:8000/diversion.html --> shouldn't this give status code 301? It showed status code 200. Max: the requested html was loaded, that is a 200. And then the browser sees in that html a redirection and loads the page http://localhost:8000/upload.html (the redirection is in the html, and does not come from the server)

localhost:8000/upload.html worked and showed 200
localhost:8000/diversion.ht worked and showed 404

**Comment by MaxIhme** [comment]
http://localhost:8000 gives 200 and 
http://localhost:8000/index.html

**Comment by MaxIhme** [comment]
when I change config to:
server
{
	autoindex off;

	location /
	{
		allowed_Methods GET POST;
		#index index.html;
	}
}
and do
http://localhost:8000/ -> 403 forbidden (correct, because autoindex is off)

set autoindex to on, 
http://localhost:8000/ -> comes the index
click on "../" -> comes the same site, because it's the root -> ok 
pictures will be shown, .ico and .txt will be downloaded -> ok for me
click on dir (a file without ending) -> 500 Server error -> ok for me (server still runs)



@MaxIhme No matter if autoindex is on or off, I get:
![image](https://github.com/RanniSch/Webserv/assets/104382315/e51e28bb-ebf7-47bb-ba2b-d416eeba4d8b)

**Comment by RanniSch** [comment]
ok
