### ISSUE TITLE
Siege & stress test: You should be able to use siege indefinitely without having to restart the server (take a look at siege -b).

### ISSUE THREAD

**Issue by RanniSch** [RanniSch/Webserv#70]
I ran the following without restarting the server:

siege -c 10 -t 1M http://localhost:8000/animal.jpg --> perfect

siege -c 10 -t 1M http://localhost:8000/upload.html --> perfect

siege -c 10 -t 1M http://localhost:8000/index.html --> perfect

siege -c 10 -t 1M http://localhost:8000/cgi-bin/script-post-2.py --> perfect

siege -b http://localhost:8000/listing_Kopie.html 
when I run it short --> perfect
when I run it super long
![image](https://github.com/RanniSch/Webserv/assets/104382315/035754ed-9a6a-440d-84b4-a660cd90cdb1)

With 27 transactions failed.

**Comment by MaxIhme** [comment]
Ahh summary from the bottom: "on mac I did not have to restart the server." Via docker it gives segfaults and bad allocs 

I ran the following: I had to restart the server because of segfault and "bad alloc" via docker. But in between came that.

on docker:
siege -c 10 -t 1M http://localhost:8000/animal.jpg
<img width="642" alt="Bildschirmfoto 2023-10-31 um 18 45 24" src="https://github.com/RanniSch/Webserv/assets/79764057/5fcb51b6-16d0-499b-a872-462d18bed632">

then on mac (because i get many segfaults and bad allocs on docker)
siege -c 10 -t 1M http://localhost:8000/upload.html
<img width="494" alt="Bildschirmfoto 2023-10-31 um 18 50 55" src="https://github.com/RanniSch/Webserv/assets/79764057/47102414-9ab0-4689-a5c4-b736d216e078">

without restarting on mac:
siege -c 10 -t 1M http://localhost:8000/index.html
<img width="444" alt="Bildschirmfoto 2023-10-31 um 18 52 47" src="https://github.com/RanniSch/Webserv/assets/79764057/a95c5b54-8b31-4209-865e-10da45a02964">

without restarting on mac: -> the script does not work on my mac (don't know why)
siege -c 10 -t 1M http://localhost:8000/cgi-bin/script-post-2.py 
<img width="708" alt="Bildschirmfoto 2023-10-31 um 18 55 11" src="https://github.com/RanniSch/Webserv/assets/79764057/8d90249c-ad96-4575-a2a7-8df26c6a78ab">

without restarting on my mac: 
siege -b http://localhost:8000/listing_Kopie.html
<img width="442" alt="Bildschirmfoto 2023-10-31 um 18 56 54" src="https://github.com/RanniSch/Webserv/assets/79764057/2a0db44a-58c7-48e5-9d60-9022e62afba6">

**Comment by RanniSch** [comment]
So let's wait for @LukasKava to test it.

**Comment by MaxIhme** [comment]
I have again a broken pipe via Docker and using siege. Did you guys saw that somehow? @RanniSch  @LukasKava ?
It happens when I do: siege -c 10 -t 1M http://localhost:8000/animal.jpg
 and then ctr + c siege

<img width="675" alt="Bildschirmfoto 2023-11-02 um 12 06 52" src="https://github.com/RanniSch/Webserv/assets/79764057/5cf189fd-d910-415f-83c6-1f28237fe739">

**Comment by MaxIhme** [comment]
I checked from the first post:
siege -c 10 -t 1M http://localhost:8000/animal.jpg -> 100% availability
after done I had a broken pipe! how about you @RanniSch @LukasKava
